#!/bin/bash
#SBATCH --job-name="clique"
#SBATCH --output="clique.%j.%N.out"
#SBATCH --partition=compute
#SBATCH --nodes=10
#SBATCH --ntasks-per-node=24
#SBATCH --export=ALL
#SBATCH -t 2:00:00
#SBATCH -A csb143

cd /home/$USER/Ramseys-bane/distributed_sys_flip/
ibrun -v ./a.out 24